############# Database Properties ##########################################
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce_db

############# JWT Properties ###########################################
jwt.secretKey=MaSuperCleSecrete123456789
jwt.expirationTimeMs=86400000
keystore.password=secret

############# Mail Properties (optionnel, commente si tu veux) ##########
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=tonemail@gmail.com
# spring.mail.password=tonmotdepasse
# spring.mail.protocol=smtp

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

################# Elasticsearch Config (commente si pas utilisé) #########
# spring.data.elasticsearch.repositories.enabled=true
# spring.data.elasticsearch.cluster-name=elasticsearch
# spring.data.elasticsearch.cluster-nodes=localhost:9300

##########################################################################
account.verification.url=http://localhost:8080/api/auth/accountVerification

server.port=8080